In [11]:
import h5py
import numpy

In [17]:
data = r"C:\Users\carina\simion_files\TOF_ML\simulations\TOF_data\R550\sim_neg_R550_pos_0_pos_0_1_n10000.h5"
f = h5py.File(data, 'r')
f['data1'].keys()
f.close()

In [13]:
for key in f['data1'].keys():
    print(f['data1'][key])
    print(f['data1'][key][()])

<HDF5 dataset "final_azimuth": shape (10000,), type "<f8">
[-0. -0. -0. ... -0. -0. -0.]
<HDF5 dataset "final_elevation": shape (10000,), type "<f8">
[0. 0. 0. ... 0. 0. 0.]
<HDF5 dataset "final_ke": shape (10000,), type "<f8">
[350.108 349.593 349.48  ... 350.033 351.135 350.886]
<HDF5 dataset "initial_azimuth": shape (10000,), type "<f8">
[0. 0. 0. ... 0. 0. 0.]
<HDF5 dataset "initial_elevation": shape (10000,), type "<f8">
[0. 0. 0. ... 0. 0. 0.]
<HDF5 dataset "initial_ke": shape (10000,), type "<f8">
[600.108 599.593 599.48  ... 600.033 601.135 600.886]
<HDF5 dataset "ion_number": shape (10000,), type "<i4">
[    1     2     3 ...  9998  9999 10000]
<HDF5 dataset "tof": shape (10000,), type "<f8">
[0.075013  0.0753539 0.0754294 ... 0.075062  0.0743476 0.074507 ]
<HDF5 dataset "x": shape (10000,), type "<f8">
[406.7 406.7 406.7 ... 406.7 406.7 406.7]
<HDF5 dataset "y": shape (10000,), type "<f8">
[0. 0. 0. ... 0. 0. 0.]
<HDF5 dataset "z": shape (10000,), type "<f8">
[0. 0. 0. ... 0.

In [15]:
f.close()